language: generic
sudo: required
services:
    - docker

defore_install:
    - docker build -t mars0007/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mars0007/docker-react npm run test
